import type {
  LearningKind,
  LearningQuestion,
  StageDefinition,
} from "../shared/types";

export type SeaRoute =
  | "open"
  | "coral-maze"
  | "bubble-column"
  | "current"
  | "split"
  | "cave"
  | "clock-gate"
  | "festival";

export type FishFormation = "arc" | "ring" | "line" | "school" | "layers";

export interface SeaStage extends StageDefinition {
  creature: string;
  creatureColor: string;
  route: SeaRoute;
  formation: FishFormation;
  current: [number, number];
  obstacleCount: number;
  visibility: number;
  depthRange: number;
  beacon: [number, number, number];
  pearlCount: number;
  scenery: string;
}

interface MissionSpec {
  title: string;
  description: string;
  mission: string;
  creature: string;
  creatureColor: string;
  route: SeaRoute;
  formation: FishFormation;
  current: [number, number];
  obstacleCount: number;
  visibility: number;
  depthRange: number;
  beacon: [number, number, number];
  targets: number;
  pearlCount: number;
  scenery: string;
  question: LearningQuestion;
}

interface SeaArea {
  area: string;
  palette: [string, string, string];
  learning: LearningKind;
  missions: MissionSpec[];
}

const q = (
  kind: LearningKind,
  prompt: string,
  choices: string[],
  answer: number,
  hint: string,
  speak = prompt,
): LearningQuestion => ({ kind, prompt, choices, answer, hint, speak });

const areas: SeaArea[] = [
  {
    area: "ひだまり サンゴ",
    palette: ["#39d7d0", "#ff8d8d", "#0b5d8f"],
    learning: "ひらがな",
    missions: [
      {
        title: "はじめての ソナー",
        description: "やさしい ひかりを たどって、クマノミを みつけよう。",
        mission: "ソナーで クマノミを 3びき みつけ、ひかりの いえへ かえろう",
        creature: "クマノミ",
        creatureColor: "#ff8057",
        route: "open",
        formation: "arc",
        current: [0, 0],
        obstacleCount: 5,
        visibility: 1,
        depthRange: 0.3,
        beacon: [0, 0.4, 7],
        targets: 3,
        pearlCount: 1,
        scenery: "sunny-coral",
        question: q("ひらがな", "「さかな」の はじめの もじは？", ["さ", "か", "な"], 0, "さ・か・な と ゆっくり よもう"),
      },
      {
        title: "こえの かいがら",
        description: "かいがらの こえを きいて、チョウチョウウオを さがそう。",
        mission: "ひかる かいがらを 2こ たどり、4ひきを たすけよう",
        creature: "チョウチョウウオ",
        creatureColor: "#ffe26a",
        route: "coral-maze",
        formation: "line",
        current: [0.04, 0],
        obstacleCount: 7,
        visibility: 0.95,
        depthRange: 0.5,
        beacon: [-5, 0.5, 6],
        targets: 4,
        pearlCount: 1,
        scenery: "shell-path",
        question: q("ひらがな", "「ひかり」の おわりの もじは？", ["ひ", "か", "り"], 2, "ひ・か・り。さいごは「り」"),
      },
      {
        title: "サンゴの まよいみち",
        description: "たかい サンゴの あいだに タツノオトシゴが かくれているよ。",
        mission: "サンゴに ぶつからず、タツノオトシゴを 4ひき あんないしよう",
        creature: "タツノオトシゴ",
        creatureColor: "#f5b15b",
        route: "coral-maze",
        formation: "layers",
        current: [-0.03, 0.02],
        obstacleCount: 10,
        visibility: 0.9,
        depthRange: 1,
        beacon: [6, 0.6, 4],
        targets: 4,
        pearlCount: 2,
        scenery: "tall-coral",
        question: q("ひらがな", "「さんご」と おなじ はじめの おとは？", ["そら", "さかな", "しお"], 1, "どちらも「さ」から はじまるよ"),
      },
      {
        title: "うみがめの おさんぽ",
        description: "ゆっくり およぐ ウミガメと ひかりの わを くぐろう。",
        mission: "5つの ひかりの わを たどり、ウミガメを いえへ つれていこう",
        creature: "ウミガメ",
        creatureColor: "#63d28e",
        route: "bubble-column",
        formation: "school",
        current: [0.02, -0.04],
        obstacleCount: 8,
        visibility: 0.88,
        depthRange: 1.2,
        beacon: [-6, 1, -5],
        targets: 4,
        pearlCount: 2,
        scenery: "turtle-garden",
        question: q("ひらがな", "「かめ」の 2もじめは？", ["か", "め", "み"], 1, "か・め。2もじめは「め」"),
      },
      {
        title: "にじサンゴの てんとう",
        description: "イルカの なかまと サンゴの ひかりを とりもどそう。",
        mission: "イルカを 5ひき あんないし、にじサンゴへ かえろう",
        creature: "イルカ",
        creatureColor: "#5bb8ff",
        route: "split",
        formation: "arc",
        current: [0.05, 0.03],
        obstacleCount: 11,
        visibility: 0.86,
        depthRange: 1.4,
        beacon: [0, 1, -8],
        targets: 5,
        pearlCount: 2,
        scenery: "rainbow-coral",
        question: q("ひらがな", "「いるか」は どれ？", ["いろか", "いるか", "いるが"], 1, "い・る・か と よもう"),
      },
    ],
  },
  {
    area: "あわの もり",
    palette: ["#55b7ff", "#d697ff", "#163a72"],
    learning: "カタカナ",
    missions: [
      {
        title: "クラゲの あわみち",
        description: "ふわふわの あわを たどって クラゲを みつけよう。",
        mission: "クラゲを 3びき みつけ、あわの もりの いえへ かえろう",
        creature: "クラゲ",
        creatureColor: "#d7a6ff",
        route: "bubble-column",
        formation: "layers",
        current: [0, 0.04],
        obstacleCount: 6,
        visibility: 0.82,
        depthRange: 1.5,
        beacon: [0, 1.2, 8],
        targets: 3,
        pearlCount: 1,
        scenery: "jelly-forest",
        question: q("カタカナ", "「くらげ」を カタカナに すると？", ["クラゲ", "グラゲ", "クラケ"], 0, "ク・ラ・ゲ。さいごは てんてんの「ゲ」"),
      },
      {
        title: "マンボウの かくれんぼ",
        description: "おおきな はっぱの うらに マンボウが いるよ。",
        mission: "ソナーを つかって マンボウを 4ひき みつけよう",
        creature: "マンボウ",
        creatureColor: "#9fc8ff",
        route: "coral-maze",
        formation: "arc",
        current: [-0.04, 0],
        obstacleCount: 9,
        visibility: 0.78,
        depthRange: 1,
        beacon: [7, 0.8, 2],
        targets: 4,
        pearlCount: 1,
        scenery: "leaf-cave",
        question: q("カタカナ", "「マンボウ」の はじめは？", ["マ", "ン", "ボ"], 0, "マ・ン・ボ・ウ と よもう"),
      },
      {
        title: "クリオネの うえと した",
        description: "あわの エレベーターで うえと したを さがそう。",
        mission: "3つの たかさに いる クリオネを あんないしよう",
        creature: "クリオネ",
        creatureColor: "#f1f6ff",
        route: "bubble-column",
        formation: "layers",
        current: [0.02, -0.02],
        obstacleCount: 10,
        visibility: 0.75,
        depthRange: 2,
        beacon: [-6, 1.4, 5],
        targets: 4,
        pearlCount: 2,
        scenery: "bubble-lift",
        question: q("カタカナ", "ただしい「クリオネ」は？", ["クリオネ", "クりオネ", "クリオヌ"], 0, "ぜんぶ カタカナの「クリオネ」"),
      },
      {
        title: "エビと カニの ぶんき",
        description: "ふたつの みちから エビの ひかりを えらぼう。",
        mission: "エビの ひかりを たどり、5ひきを ひとつの むれにしよう",
        creature: "エビ",
        creatureColor: "#ff7f7f",
        route: "split",
        formation: "line",
        current: [0.05, -0.03],
        obstacleCount: 12,
        visibility: 0.72,
        depthRange: 1.3,
        beacon: [6, 1, -6],
        targets: 5,
        pearlCount: 2,
        scenery: "forked-forest",
        question: q("カタカナ", "「エビ」の さいごは？", ["エ", "ヒ", "ビ"], 2, "エ・ビ。てんてんの「ビ」"),
      },
      {
        title: "あわの おおきな き",
        description: "タコと いっしょに おおきな あわの きを ひからせよう。",
        mission: "あわの うずを こえて タコを 5ひき あんないしよう",
        creature: "タコ",
        creatureColor: "#ff739b",
        route: "festival",
        formation: "ring",
        current: [-0.06, 0.05],
        obstacleCount: 14,
        visibility: 0.7,
        depthRange: 1.8,
        beacon: [0, 1.5, -9],
        targets: 5,
        pearlCount: 2,
        scenery: "great-bubble-tree",
        question: q("カタカナ", "「たこ」を カタカナに すると？", ["タコ", "ダコ", "ナコ"], 0, "タ・コ と よもう"),
      },
    ],
  },
  {
    area: "しおの たに",
    palette: ["#22a6b3", "#75e6b6", "#123b5d"],
    learning: "たしざん",
    missions: [
      {
        title: "ふたつの むれ",
        description: "ふたつの みちの イカを ひとつの むれに。",
        mission: "2ひきと 2ひきの イカを あつめて かえろう",
        creature: "イカ",
        creatureColor: "#f4d8ff",
        route: "split",
        formation: "line",
        current: [0.07, 0],
        obstacleCount: 8,
        visibility: 0.8,
        depthRange: 1,
        beacon: [0, 0.8, 8],
        targets: 4,
        pearlCount: 1,
        scenery: "twin-stream",
        question: q("たしざん", "2ひきと 2ひき。みんなで？", ["3びき", "4ひき", "5ひき"], 1, "2＋2は4"),
      },
      {
        title: "エイの ごうりゅう",
        description: "しおの ながれを よんで エイを ごうりゅうさせよう。",
        mission: "3びきと 2ひきの エイを ひかりの いえへ",
        creature: "エイ",
        creatureColor: "#82c9e8",
        route: "current",
        formation: "arc",
        current: [0.09, -0.02],
        obstacleCount: 10,
        visibility: 0.76,
        depthRange: 1.2,
        beacon: [-7, 1, 5],
        targets: 5,
        pearlCount: 1,
        scenery: "ray-valley",
        question: q("たしざん", "3＋2は いくつ？", ["4", "5", "6"], 1, "3から 2つ すすもう"),
      },
      {
        title: "トビウオの みっつみち",
        description: "3つの しおみちに わかれた トビウオを あつめよう。",
        mission: "2ひき、3びき、1ぴきの むれを ごうりゅうさせよう",
        creature: "トビウオ",
        creatureColor: "#6de0ed",
        route: "split",
        formation: "school",
        current: [-0.06, 0.08],
        obstacleCount: 12,
        visibility: 0.74,
        depthRange: 1.4,
        beacon: [7, 1.1, -4],
        targets: 6,
        pearlCount: 2,
        scenery: "three-currents",
        question: q("たしざん", "2＋3＋1は いくつ？", ["5", "6", "7"], 1, "2＋3は5。もう1で6"),
      },
      {
        title: "マグロの きゅうりゅう",
        description: "つよい しおを よこぎって マグロを みつけよう。",
        mission: "4ひきと 4ひきの マグロを あんないしよう",
        creature: "マグロ",
        creatureColor: "#5086c9",
        route: "current",
        formation: "line",
        current: [0.12, 0.05],
        obstacleCount: 14,
        visibility: 0.7,
        depthRange: 1.6,
        beacon: [-8, 1.2, -5],
        targets: 8,
        pearlCount: 2,
        scenery: "fast-current",
        question: q("たしざん", "4＋4は いくつ？", ["7", "8", "9"], 1, "4が ふたつで8"),
      },
      {
        title: "しおの たにの とうだい",
        description: "ナンヨウハギを あつめ、たにの とうだいを つけよう。",
        mission: "6ぴきと 5ひきを ごうりゅうさせて とうだいへ",
        creature: "ナンヨウハギ",
        creatureColor: "#3f6fff",
        route: "festival",
        formation: "school",
        current: [0.1, -0.09],
        obstacleCount: 16,
        visibility: 0.68,
        depthRange: 1.8,
        beacon: [0, 1.5, -10],
        targets: 11,
        pearlCount: 2,
        scenery: "current-lighthouse",
        question: q("たしざん", "6＋5は いくつ？", ["10", "11", "12"], 1, "6に4で10。もう1で11"),
      },
    ],
  },
  {
    area: "よるの どうくつ",
    palette: ["#142850", "#6f5cff", "#34e7e4"],
    learning: "ひきざん",
    missions: [
      {
        title: "ホタルイカの あかり",
        description: "くらい みちで ホタルイカの ひかりを たどろう。",
        mission: "7ひきの うち 3びきを さきに いえへ あんないしよう",
        creature: "ホタルイカ",
        creatureColor: "#5ffcff",
        route: "cave",
        formation: "line",
        current: [0.02, 0],
        obstacleCount: 9,
        visibility: 0.56,
        depthRange: 1,
        beacon: [0, 0.8, 7],
        targets: 4,
        pearlCount: 1,
        scenery: "glow-cave",
        question: q("ひきざん", "7ひきから 3びき かえった。のこりは？", ["3びき", "4ひき", "5ひき"], 1, "7－3は4"),
      },
      {
        title: "キンメダイの いわとびら",
        description: "ひかりを あつめて いわの とびらを あけよう。",
        mission: "10ぴきから 4ひき かえった あとの なかまを さがそう",
        creature: "キンメダイ",
        creatureColor: "#ff5f72",
        route: "cave",
        formation: "arc",
        current: [-0.03, 0.02],
        obstacleCount: 11,
        visibility: 0.52,
        depthRange: 1.2,
        beacon: [-6, 1, 5],
        targets: 6,
        pearlCount: 1,
        scenery: "rock-gate",
        question: q("ひきざん", "10－4は いくつ？", ["5", "6", "7"], 1, "10から4つ もどろう"),
      },
      {
        title: "アンコウの みちしるべ",
        description: "アンコウの ライトで 3つの へやを めぐろう。",
        mission: "12ひきから 5ひき かえった のこりを あんないしよう",
        creature: "アンコウ",
        creatureColor: "#e7f06a",
        route: "coral-maze",
        formation: "layers",
        current: [0.04, -0.04],
        obstacleCount: 13,
        visibility: 0.48,
        depthRange: 1.6,
        beacon: [7, 1.2, 3],
        targets: 7,
        pearlCount: 2,
        scenery: "lantern-rooms",
        question: q("ひきざん", "12－5は いくつ？", ["6", "7", "8"], 1, "12から5つ もどると7"),
      },
      {
        title: "ウミウシの ひかりばたけ",
        description: "ちいさな ひかりを みおとさずに さがそう。",
        mission: "15ひきから 8ひき かえった あとの ウミウシを みつけよう",
        creature: "ウミウシ",
        creatureColor: "#ff70cc",
        route: "split",
        formation: "ring",
        current: [-0.05, -0.03],
        obstacleCount: 15,
        visibility: 0.44,
        depthRange: 1.8,
        beacon: [-7, 1.4, -5],
        targets: 7,
        pearlCount: 2,
        scenery: "glow-meadow",
        question: q("ひきざん", "15－8は いくつ？", ["6", "7", "8"], 1, "15から5で10。さらに3ひいて7"),
      },
      {
        title: "りゅうぐうの おおひかり",
        description: "ながい リュウグウノツカイを おおひかりへ みちびこう。",
        mission: "18ひきから 9ひき かえった のこりを ひとつの むれに",
        creature: "リュウグウノツカイ",
        creatureColor: "#f4efff",
        route: "festival",
        formation: "school",
        current: [0.06, 0.06],
        obstacleCount: 17,
        visibility: 0.42,
        depthRange: 2,
        beacon: [0, 1.6, -10],
        targets: 9,
        pearlCount: 2,
        scenery: "dragon-light",
        question: q("ひきざん", "18－9は いくつ？", ["8", "9", "10"], 1, "18は9と9に わけられるよ"),
      },
    ],
  },
  {
    area: "ときの リーフ",
    palette: ["#3b70d4", "#ffd15c", "#342b64"],
    learning: "とけい",
    missions: [
      {
        title: "3じの しおもん",
        description: "3じに ひらく しおもんを くぐろう。",
        mission: "コウイカを 3びき みつけ、3じの しおもんへ かえろう",
        creature: "コウイカ",
        creatureColor: "#fff0b7",
        route: "clock-gate",
        formation: "arc",
        current: [0.03, 0],
        obstacleCount: 8,
        visibility: 0.72,
        depthRange: 1,
        beacon: [0, 1, 8],
        targets: 3,
        pearlCount: 1,
        scenery: "three-clock",
        question: q("とけい", "ながい はりが12、みじかい はりが3。なんじ？", ["2じ", "3じ", "3じはん"], 1, "みじかい はりが3なら3じ"),
      },
      {
        title: "5じはんの かい",
        description: "5じ30ぷんに ひらく かいがらの いえ。",
        mission: "オウムガイを 4ひき みつけ、5じはんに かえろう",
        creature: "オウムガイ",
        creatureColor: "#f5c084",
        route: "clock-gate",
        formation: "ring",
        current: [-0.04, 0.02],
        obstacleCount: 10,
        visibility: 0.7,
        depthRange: 1.2,
        beacon: [-6, 1, 5],
        targets: 4,
        pearlCount: 1,
        scenery: "half-past-shell",
        question: q("とけい", "5じ30ぷんは どれ？", ["5じ", "5じはん", "6じはん"], 1, "30ぷんは「はん」"),
      },
      {
        title: "8じの あさリーフ",
        description: "あさ8じに デバスズメダイが あつまるよ。",
        mission: "あさの ひかりを たどり、5ひきを あんないしよう",
        creature: "デバスズメダイ",
        creatureColor: "#72e7ff",
        route: "split",
        formation: "school",
        current: [0.05, -0.03],
        obstacleCount: 12,
        visibility: 0.68,
        depthRange: 1.4,
        beacon: [7, 1.2, -3],
        targets: 5,
        pearlCount: 2,
        scenery: "morning-reef",
        question: q("とけい", "8じ ちょうど。ながい はりは？", ["12", "8", "6"], 0, "ちょうどの ながい はりは12"),
      },
      {
        title: "9じ15ふんの しお",
        description: "15ふんで かわる しおを よんで すすもう。",
        mission: "ハリセンボンを 5ひき みつけ、9じ15ふんの もんへ",
        creature: "ハリセンボン",
        creatureColor: "#f3d26f",
        route: "current",
        formation: "line",
        current: [0.09, 0.06],
        obstacleCount: 14,
        visibility: 0.65,
        depthRange: 1.6,
        beacon: [-8, 1.3, -5],
        targets: 5,
        pearlCount: 2,
        scenery: "quarter-current",
        question: q("とけい", "9じ15ふん。ながい はりは どこ？", ["3", "6", "9"], 0, "15ふんで ながい はりは3"),
      },
      {
        title: "12じの ときサンゴ",
        description: "12じに ときサンゴを ぜんぶ ひからせよう。",
        mission: "ジンベエザメを 6ぴき あんないし、おおきな もんへ かえろう",
        creature: "ジンベエザメ",
        creatureColor: "#597ea9",
        route: "festival",
        formation: "arc",
        current: [-0.07, 0.08],
        obstacleCount: 16,
        visibility: 0.62,
        depthRange: 1.8,
        beacon: [0, 1.6, -10],
        targets: 6,
        pearlCount: 2,
        scenery: "time-coral",
        question: q("とけい", "12じ ちょうど。ふたつの はりは？", ["どちらも12", "どちらも6", "3と12"], 0, "12じは どちらも12"),
      },
    ],
  },
  {
    area: "ひかりの しんかい",
    palette: ["#071b3b", "#3cf4d7", "#ff65cb"],
    learning: "かんさつ",
    missions: [
      {
        title: "グソクムシの いわみち",
        description: "いわの したを てらして、ちいさな なかまを みつけよう。",
        mission: "ダイオウグソクムシを 3びき みつけ、ひかりの いえへ",
        creature: "ダイオウグソクムシ",
        creatureColor: "#a8b8d0",
        route: "cave",
        formation: "line",
        current: [0.03, -0.03],
        obstacleCount: 12,
        visibility: 0.45,
        depthRange: 1.4,
        beacon: [0, 1.2, 8],
        targets: 3,
        pearlCount: 1,
        scenery: "stone-path",
        question: q("ひらがな", "「ひかり」の まんなかは？", ["ひ", "か", "り"], 1, "ひ・か・り。まんなかは「か」"),
      },
      {
        title: "ミズクラゲの にじ",
        description: "くらい うみで ミズクラゲが にじを つくるよ。",
        mission: "4ひきの ミズクラゲを ひとつの わにしよう",
        creature: "ミズクラゲ",
        creatureColor: "#b8a9ff",
        route: "bubble-column",
        formation: "ring",
        current: [-0.04, 0.05],
        obstacleCount: 13,
        visibility: 0.43,
        depthRange: 1.8,
        beacon: [-6, 1.4, 5],
        targets: 4,
        pearlCount: 1,
        scenery: "jelly-rainbow",
        question: q("カタカナ", "「みずくらげ」を カタカナに すると？", ["ミズクラゲ", "ミスグラゲ", "ミズクラケ"], 0, "ミ・ズ・ク・ラ・ゲ"),
      },
      {
        title: "5ひきの シーラカンス",
        description: "ふるい いわの へやを めぐって なかまを あつめよう。",
        mission: "2ひきと 3びきの シーラカンスを ごうりゅうさせよう",
        creature: "シーラカンス",
        creatureColor: "#5da0a3",
        route: "split",
        formation: "school",
        current: [0.06, 0.04],
        obstacleCount: 15,
        visibility: 0.4,
        depthRange: 2,
        beacon: [7, 1.5, -4],
        targets: 5,
        pearlCount: 2,
        scenery: "ancient-rooms",
        question: q("たしざん", "2＋3は いくつ？", ["4", "5", "6"], 1, "2に3を たして5"),
      },
      {
        title: "のこりの メンダコ",
        description: "ひかりの かげに かくれた メンダコを さがそう。",
        mission: "10ぴきから 4ひき かえった あとの なかまを あんないしよう",
        creature: "メンダコ",
        creatureColor: "#ff8fc4",
        route: "current",
        formation: "layers",
        current: [-0.09, -0.05],
        obstacleCount: 16,
        visibility: 0.38,
        depthRange: 2.1,
        beacon: [-8, 1.5, -6],
        targets: 6,
        pearlCount: 2,
        scenery: "shadow-current",
        question: q("ひきざん", "10－4は いくつ？", ["5", "6", "7"], 1, "10から4つ もどると6"),
      },
      {
        title: "ひかりの うみまつり",
        description: "ぜんぶの うみの なかまと ひかりを つなごう。",
        mission: "6ぴきの ダイオウイカを あんないし、7じはんの まつりへ",
        creature: "ダイオウイカ",
        creatureColor: "#ff69d4",
        route: "festival",
        formation: "arc",
        current: [0.1, -0.09],
        obstacleCount: 18,
        visibility: 0.42,
        depthRange: 2.3,
        beacon: [0, 1.8, -11],
        targets: 6,
        pearlCount: 3,
        scenery: "grand-light-festival",
        question: q("とけい", "うみまつりは 7じ30ぷん。どれ？", ["7じ", "7じはん", "8じはん"], 1, "30ぷんは「はん」"),
      },
    ],
  },
];

export const seaStages: SeaStage[] = areas.flatMap((area, areaIndex) =>
  area.missions.map((mission, missionIndex) => {
    const number = areaIndex * 5 + missionIndex + 1;
    return {
      id: `shinkai-${String(number).padStart(2, "0")}`,
      area: area.area,
      areaIndex,
      title: mission.title,
      description: mission.description,
      mission: mission.mission,
      learning: mission.question.kind,
      difficulty: (missionIndex < 2 ? 1 : missionIndex < 4 ? 2 : 3) as 1 | 2 | 3,
      palette: area.palette,
      seed: 1301 + number * 113,
      targets: mission.targets,
      bonusTargets: mission.pearlCount,
      question: mission.question,
      variant: `${mission.route}:${mission.scenery}`,
      creature: mission.creature,
      creatureColor: mission.creatureColor,
      route: mission.route,
      formation: mission.formation,
      current: mission.current,
      obstacleCount: mission.obstacleCount,
      visibility: mission.visibility,
      depthRange: mission.depthRange,
      beacon: mission.beacon,
      pearlCount: mission.pearlCount,
      scenery: mission.scenery,
    };
  }),
);

export const isSeaStage = (stage: StageDefinition): stage is SeaStage =>
  "creature" in stage && typeof (stage as Partial<SeaStage>).creature === "string";
